export const data = {
    users: [
        {
            id: '1',
            name: 'Quốc Thắng',
            email: 'quocthang@gmail.com',
            password: '1',
            img: require("./src/img/user/1.jpg"),
        },
        {
            id: '2',
            name: 'Đỗ Thị Ánh Huyền',
            email: 'huyen234@gmail.com',
            password: '1',
            img: require("./src/img/category/book.png"),
        },
        {
            id: '3',
            name: 'Hồ Thị Nhung',
            email: 'nhung123@gmail.com',
            password: '1',
            img: require("./src/img/category/toys.png"),
        },
    ],
    Categories: [
        {
            id: '1',
            name: 'Sách',
            img: require("./src/img/category/book.png"),
        },
        {
            id: '2',
            name: 'Đồ dùng học tập ',
            img: require('./src/img/category/school-bag.png'),
        },
        {
            id: '3',
            name: 'Đồ chơi ',
            img: require('./src/img/category/snow-globe.png'),
        },
        {
            id: '4',
            name: 'Lưu niệm ',
            img: require('./src/img/category/toys.png'),
        },
    ],
    Products: [
        {
            id: '1',
            name: 'Oxford Advanced Learners Dictionary With Vietnamese Translation (Paperback) ',
            prices: '593.750 đ',
            pricesStock: '625.000 ',
            sale: '-5%',
            img: require("./src/img/products/Rectangle62.png"),
        },
        {
            id: '2',
            name: 'Tết Ở Làng Địa Ngục - Tặng Kèm Postcard',
            prices: '125.000 đ',
            pricesStock: '169.000 ',
            sale: '-26%',
            img: require("./src/img/products/Rectangle61.png"),
        },
        {
            id: '3',
            name: '100 Kỹ Năng Sinh Tồn',
            prices: '61.380 đ',
            pricesStock: '99.000 ',
            sale: '-38%',
            img: require("./src/img/products/Rectangle63.png"),
        },
        {
            id: '4',
            name: 'Xưởng Phép Thuật - Atelier Of Witch Hat - Tập 12',
            prices: '45.000 đ',
            pricesStock: '50.000 ',
            sale: '-10%',
            img: require("./src/img/products/Rectangle64.png"),
        },
        {
            id: '5',
            name: 'Đồ Chơi Mô Hình Cầu Tuyết Disney Frozen II - 52 Toys 6958985023955',
            prices: '266.000 đ',
            pricesStock: '280.000 ',
            sale: '-5%',
            img: require("./src/img/products/Rectangle65.png"),
        },
        {
            id: '6',
            name: 'Hộp Quà Có Đèn Trang Trí Giáng Sinh 13 cm - 2282 - Hình Gấu',
            prices: '162.060 đ',
            pricesStock: '222.000 ',
            sale: '-27%',
            img: require("./src/img/products/Rectangle66.png"),
        },
    ],
    Book: [
        {
            id: '1',
            name: 'Ghi Chép Pháp Y - Những Cái Chết Bí Ẩn',
            img: require('./src/img/book/75.png'),
            supplier: 'AZ Việt Nam',
            ublishing: 'Thanh Niên',
            author: 'Lưu Hiểu Huy',
            cover: 'Bìa Mềm',
            price: '150.000 đ ',
            des:'GHI CHÉP PHÁP Y - NHỮNG CÁI CHẾT BÍ ẨN – GHI CHÉP PHÁP Y - NHỮNG CÁI CHẾT BÍ ẨN –Làm cách nào để một “xác chết lên tiếng”? - đó là công việc của bác sĩ pháp y.“Ghi chép pháp y - Những cái chết bí ẩn” là cuốn sách nằm trong hệ liệt với “Pháp y Tần Minh” - bộ tiểu thuyết nổi đình đám của xứ Trung đã được chuyển thể thành series phim. Cuốn sách tổng hợp những vụ án có thật, được viết bởi bác sĩ pháp y Lưu Hiểu Huy - người có 15 năm kinh nghiệm và từng mổ xẻ hơn 800 tử thi.Trải qua 15 câu chuyện kinh hoàng, cuốn sách sẽ đưa bạn bước vào hiện trường của những vụ án man rợ như: xác chết phi tang dưới cánh đồng ngô, thi thể thiếu nữ không lành lặn, xác chết nhầy nhụa đang bị giòi bọ đục khoét hay một thi thể co cứng trong màng bọc nilon…lần theo những dấu vết, ghép lại sự thật từ những mảnh vụn thi thể, nguyên nhân của cái chết sẽ dần được hé mở. Mỗi vụ án đều là một ẩn số, hiện trường vụ án bao gồm cả xác chết chính là chiếc chìa khóa để truy tìm hung thủ ngay cả khi nó không còn nguyên vẹn. Vậy làm cách để các bác sĩ pháp y có thể xác định thương tật, các dấu hiệu cơ thể bị xâm hại? Cuốn sách này sẽ trình bày những kiến thức chuyên môn và quy trình xử lý vụ án, từ hiện trường vụ án đến đài giải phẫu, xét nghiệm nội tạng, phân tích chất độc… từng bước tìm ra bí mật ẩn giấu sau mỗi tử thi, phơi bày những manh mối liên quan đến tội ác con người và lỗ hổng của xã hội.Không chỉ thuật lại những vụ án và các phương pháp pháp y, cuốn sách còn chứa đựng cảm xúc của tác giả đối với nghề nghiệp và sự méo mó của bản chất con người. Chẳng hạn, một đứa trẻ bệnh nặng phải đau đớn đến thế nào khi bị người nhà đem ra làm công cụ để đòi bồi thường? Cuốn sách sẽ phơi bày những góc khuất của xã hội, những hành vi thủ ác, sự biến chất và mất nhân tính của một bộ phận con người trong xã hội.Nếu bạn tò mò muốn biết cách đánh giá tuổi của người chết dựa trên mức độ mòn răng? Hay cách dùng một con giòi từ người chết để suy ra thời điểm chính xác của vụ án giết người? Hy vọng cuốn sách này sẽ cho bạn trải nghiệm khó quên về nghề pháp y.'
        },
        {
            id: '2',
            name: 'Thiên Tài Bên Trái, Kẻ Điên Bên Phải (Tái Bản 2021)',
            img: require('./src/img/book/76.png'),
            supplier: 'AZ Việt Nam',
            ublishing: 'Thế Giới',
            author: 'Cao Minh',
            cover: 'Bìa Mềm',
            price: '125.300 đ ',
            des:'Thiên Tài Bên Trái, Kẻ Điên Bên Phải - NẾU MỘT NGÀY ANH THẤY TÔI ĐIÊN, THỰC RA CHÍNH LÀ ANH ĐIÊN ĐẤY! - Hỡi những con người đang oằn mình trong cuộc sống, bạn biết gì về thế giới của mình? Là vô vàn thứ lý thuyết được các bậc vĩ nhân kiểm chứng, là luật lệ, là cả nghìn thứ sự thật bọc trong cái lốt hiển nhiên, hay những triết lý cứng nhắc của cuộc đời? - Lại đây, vượt qua thứ nhận thức tẻ nhạt bị đóng kín bằng con mắt trần gian, khai mở toàn bộ suy nghĩ, để dòng máu trong bạn sục sôi trước những điều kỳ vĩ, phá vỡ mọi quy tắc. Thế giới sẽ gọi bạn là kẻ điên, nhưng vậy thì có sao? Ranh giới duy nhất giữa kẻ điên và thiên tài chẳng qua là một sợi chỉ mỏng manh: Thiên tài chứng minh được thế giới của mình, còn kẻ điên chưa kịp làm điều đó. Chọn trở thành một kẻ điên để vẫy vùng giữa nhân gian loạn thế hay khóa hết chúng lại, sống mãi một cuộc đời bình thường khiến bạn cảm thấy hạnh phúc hơn? - Thiên tài bên trái, kẻ điên bên phải là cuốn sách dành cho những người điên rồ, những kẻ gây rối, những người chống đối, những mảnh ghép hình tròn trong những ô vuông không vừa vặn… những người nhìn mọi thứ khác biệt, không quan tâm đến quy tắc. Bạn có thể đồng ý, có thể phản đối, có thể vinh danh hay lăng mạ họ, nhưng điều duy nhất bạn không thể làm là phủ nhận sự tồn tại của họ. Đó là những người luôn tạo ra sự thay đổi trong khi hầu hết con người chỉ sống rập khuôn như một cái máy. Đa số đều nghĩ họ thật điên rồ nhưng nếu nhìn ở góc khác, ta lại thấy họ thiên tài. Bởi chỉ những người đủ điên nghĩ rằng họ có thể thay đổi thế giới mới là những người làm được điều đó. - Chào mừng đến với thế giới của những kẻ điên.'
        },
        {
            id: '3',
            name: 'Oxford Advanced Learner Dictionary With Vietnamese Translation (Paperback)',
            img: require('./src/img/book/77.png'),
            supplier: 'CÔNG TY TNHH EDUCATION SOLUTIONS VIỆT NAM',
            ublishing: 'Trẻ',
            author: 'Joanna Turnbull',
            cover: 'Bìa Mềm',
            price: '562.500 đ ',
            des:'Oxford Advanced Learner Dictionary (viết tắt: OALD) - từ điển bán chạy nhất thế giới - vừa ra mắt ấn bản Anh - Việt. Để cuốn sách này đến tay bạn đọc trong nước, đơn vị thực hiện mất hơn một năm làm việc với đối tác là Nhà xuất bản Oxford, từ việc xây dựng quy trình làm việc, thành lập nhóm biên dịch đến tìm kiếm đơn vị phần mềm tại nước ngoài để chuyển tải dữ liệu gốc. Sau đó, Giáo sư - tiến sĩ Nguyễn Văn Hiệp - Viện Trưởng Viện Ngôn ngữ học, Phó giáo sư - tiến sĩ Đinh Điền, học giả Fulbright Trần Mạnh Quang cùng đội ngũ hơn 30 chuyên gia biên dịch trong lĩnh vực từ điển bắt tay thực hiện ấn phẩm. - OALD phiên bản 8.0 là từ điển bán chạy nhất thế giới với hơn 35 triệu bản với những ưu điểm nổi bật: - Từ điển với dung lượng đồ sộ gồm 184,500 từ, cụm từ được giải thích một cách dễ hiểu, chính xác, trong đó có 1.000 từ và nghĩa mới. - Oxford 3000 Plus với 3000 đầu mục các từ và nghĩa thông dụng nhất giúp người học phát triển vốn từ nhanh chóng. - Oxford Writing Tutor hướng dẫn người học cách viết nhiều thể loại văn bản trong tiếng Anh; đồng thời cũng hướng dẫn người học cách phát triển ý tưởng cho bài viết của mình. - Topic Collocations, Synonym Note và Laguage Bank giúp người học chọn và sử dụng đúng, đa dạng các từ, cụm từ và các câu trong Anh ngữ'
        },
        {
            id: '4',
            name: 'Combo Sách Đám Trẻ Ở Đại Dương Đen + Đứa Trẻ Hiểu Chuyện Thường Không Có Kẹo Ăn (Bộ 2 Cuốn)',
            img: require('./src/img/book/78.png'),
            supplier: 'AZ Việt Nam',
            ublishing: 'Thế Giới, Văn Học',
            author: 'Châu Sa Đáy Mắt, Nguyên Anh',
            cover: 'Bìa Mềm',
            price: '164.255 đ ',
            des:'Combo Sách Đám Trẻ Ở Đại Dương Đen + Đứa Trẻ Hiểu Chuyện Thường Không Có Kẹo Ăn (Bộ 2 Cuốn) - 1. Đám Trẻ Ở Đại Dương Đen - Đám trẻ ở đại dương đen là lời độc thoại và đối thoại của những đứa trẻ ở đại dương đen, nơi từng lớp sóng của nỗi buồn và tuyệt vọng không ngừng cuộn trào, lúc âm ỉ, khi dữ dội. Những đứa trẻ ấy phải vật lộn trong những góc tối tâm lý, với sự u uất đè nén từ tổn thương khi không được sinh ra trong một gia đình toàn vẹn, ấm êm, khi phải mang trên đôi vai non dại những gánh nặng không tưởng. - Song song đó cũng là quá trình tự chữa lành vô cùng khó khăn của đám trẻ, cố gắng vươn mình ra khỏi đại dương đen, tìm cho mình một ánh sáng. Và chính những sự nỗ lực xoa dịu chính mình đó đã hóa thành những câu từ trong cuốn sách này, bất kể đau đớn thế nào. - Cuốn sách được viết bởi Châu Sa Đáy Mắt, một tác giả GenZ mong muốn cùng các bạn trẻ bộc bạch và vỗ về những xúc cảm chân thật về gia đình, xã hội và chính bản thân. - Sách được phát hành bởi Wavebooks - thương hiệu sách dành cho người Việt trẻ. - 2. Đứa Trẻ Hiểu Chuyện Thường Không Có Kẹo Ăn - “Đứa trẻ hiểu chuyện thường không có kẹo ăn” – Cuốn sách dành cho những thời thơ ấu đầy vết thương. - Trên đời này có một điều rất kỳ diệu, đó là bậc phụ huynh nào cũng mong muốn con mình trở nên hoàn hảo theo một hình mẫu giống hệt nhau. - Lanh lẹ, khôn khéo, dễ thương, luôn nhìn cha mẹ với gương mặt tươi cười trong sáng. - Khi người lớn yêu cầu chúng làm gì đó, chúng sẽ vui vẻ làm theo. Không phàn nàn, không oán trách, không cáu gắt, lại càng không phản kháng cãi cự.'
        },
        {
            id: '5',
            name: 'Your One Word - Dẫn Lối Sự Nghiệp Và Sống Một Cuộc Đời Ý Nghĩ',
            img: require('./src/img/book/79.png'),
            supplier: 'Rio Book',
            ublishing: 'Dân Trí',
            author: 'Evan Carmichael',
            cover: 'Bìa Mềm',
            price: '157.250 đ ',
            des:'YOUR ONE WORD - "DẪN LỐI SỰ NGHIỆP VÀ SỐNG MỘT CUỘC ĐỜI CÓ Ý NGHĨA" là cuốn sách mở đường cho dòng sách Hashtag Inspiration, một cuốn sách mang đến tư duy cần có để trở thành một người thành công và sống một cuộc đời ý nghĩa: Tư duy Từ khoá. - Nếu bạn chỉ được dùng một từ duy nhất để miêu tả bản thân và sự nghiệp của mình, thì từ đó sẽ là gì? - Chúng tôi dám chắc rằng không phải ai cũng có câu trả lời. Bởi hầu hết mọi người đều đang sống một cuộc sống tầm thường, không biết mình là ai và mục tiêu của mình là gì. Mỗi ngày, bạn thức dậy và đi làm một công việc mà mình không hề yêu thích. Bạn sống chỉ để trông mong những buổi tối và cuối tuần, rồi ước rằng khoảng thời gian dành cho công việc đừng nhàm chán đến thế. - Đó là lý do mà cuốn sách “YOUR ONE WORD - Dẫn lối sự nghiệp và sống một cuộc đời ý nghĩa” sẽ khiến bạn phải xem xét lại niềm tin và cách nhìn nhận thế giới với Tư duy Từ Khóa. Không chỉ đơn thuần là một từ định nghĩa bản thân và sự nghiệp, nó còn giúp bạn xác định tôn chỉ và triết lý sống để mở khóa tiềm năng và tạo ra một thế giới mà bạn chưa từng biết là tồn tại. - Bằng giọng văn truyền cảm hứng và chân thành của Evan Carmichael - Doanh nhân kiêm Diễn giả/ Youtuber sở hữu 2,54 triệu người theo dõi nổi tiếng trên toàn thế giới sẽ cùng bạn.'
        },
        {
            id: '6',
            name: 'Ba Từ Nhiệm Màu - Bí Quyết Ttrở Thành Những Bậc Cha Mẹ Trẻ Hằng Mong Ước',
            img: require('./src/img/book/80.png'),
            supplier: 'Tân Việt',
            ublishing: 'Lao Động',
            author: 'Saito Takashi',
            cover: 'Bìa Mềm',
            price: '46.750 đ ',
            des:'Ba Từ Nhiệm Màu - Bí Quyết Trở Thành Những Bậc Cha Mẹ Trẻ Hằng Mong Ước - Gia đình là cái nôi văn hóa đầu tiên hình thành nên nhân cách của trẻ. Sự khéo lésách thiếu nhio trong giao tiếp và kiên định với phương châm giáo dục trẻ là điều vô cùng quan trọng. Tác giả Saito Takashi đã ngầm khẳng định không thể chủ quan khi cho rằng "cha mẹ sinh con trời sinh tính" mà câu nói "ở bầu thì tròn ở ống thì dài" sẽ chính xác hơn. Cuốn sách xoay quanh vấn đề về việc rèn luyện tư duy cho trẻ thông qua học tập. Và thói quen học tập hay bất cứ một loại động lực nào trong cuộc sống hàng ngày của trử có được, cha mẹ biết cách thúc đẩy và duy trì bằng ba cụm từ "có phép màu".'
        },
        {
            id: '7',
            name: 'Cây Cam Ngọt Của Tôi',
            img: require('./src/img/book/81.png'),
            supplier: 'Nhã Nam',
            ublishing: 'Hội Nhà Văn',
            author: 'José Mauro de Vasconcelos',
            cover: 'Bìa Mềm',
            price: '75.600 đ ',
            des:'“Vị chua chát của cái nghèo hòa trộn với vị ngọt ngào khi khám phá ra những điều khiến cuộc đời này đáng sống... một tác phẩm kinh điển của Brazil.” - Booklist - “Một cách nhìn cuộc sống gần như hoàn chỉnh từ con mắt trẻ thơ… có sức mạnh sưởi ấm và làm tan nát cõi lòng, dù người đọc ở lứa tuổi nào.” - The National - Hãy làm quen với Zezé, cậu bé tinh nghịch siêu hạng đồng thời cũng đáng yêu bậc nhất, với ước mơ lớn lên trở thành nhà thơ cổ thắt nơ bướm. Chẳng phải ai cũng công nhận khoản “đáng yêu” kia đâu nhé. Bởi vì, ở cái xóm ngoại ô nghèo ấy, nỗi khắc khổ bủa vây đã che mờ mắt người ta trước trái tim thiện lương cùng trí tưởng tượng tuyệt vời của cậu bé con năm tuổi.- Có hề gì đâu bao nhiêu là hắt hủi, đánh mắng, vì Zezé đã có một người bạn đặc biệt để trút nỗi lòng: cây cam ngọt nơi vườn sau. Và cả một người bạn nữa, bằng xương bằng thịt, một ngày kia xuất hiện, cho cậu bé nhạy cảm khôn sớm biết thế nào là trìu mến, thế nào là nỗi đau, và mãi mãi thay đổi cuộc đời cậu. - Mở đầu bằng những thanh âm trong sáng và kết thúc lắng lại trong những nốt trầm hoài niệm, Cây cam ngọt của tôi khiến ta nhận ra vẻ đẹp thực sự của cuộc sống đến từ những điều giản dị như bông hoa trắng của cái cây sau nhà, và rằng cuộc đời thật khốn khổ nếu thiếu đi lòng yêu thương và niềm trắc ẩn. Cuốn sách kinh điển này bởi thế không ngừng khiến trái tim người đọc khắp thế giới thổn thức, kể từ khi ra mắt lần đầu năm 1968 tại Brazil.'
        },
        {
            id: '8',
            name: '10-Year Record Of BTS - Beyond The Story',
            img: require('./src/img/book/82.png'),
            supplier: 'AZ Việt Nam',
            ublishing: 'Thế Giới',
            author: 'BTS, Myeongseok Kang',
            cover: 'Bìa Cứng',
            price: '529.000 đ ',
            des:'10-Year Recond Of BTS - Beyond The Story - CUỐN SÁCH CHÍNH THỨC ĐẦU TIÊN được phát hành nhân dịp kỷ niệm mười năm thành lập của BTS. - Những câu chuyện vượt xa những gì bạn đã biết về BTS. - BTS, viết tắt của “Bangtan Sonyeondan” hoặc “Beyond the Scene”, là một nhóm nhạc nam từng được đề cử giải Grammy đến từ Hàn Quốc đã chiếm được cảm tình của hàng triệu người hâm mộ trên toàn cầu kể từ khi ra mắt vào tháng 6 năm 2013. Các thành viên của BTS gồm có RM, Jin, SUGA, j-hope, Jimin, V và Jung Kook. Họ đã được đón nhận trên toàn thế giới, vượt qua mọi quốc gia, chủng tộc, ngôn ngữ, giới tính và thế hệ bằng âm nhạc, những màn trình diễn cuồng nhiệt và mối liên hệ chặt chẽ của họ với người hâm mộ. Họ luôn tìm kiếm những lối đi mới mẻ để đáp lại tình yêu mà họ nhận được thông qua âm nhạc của mình. - Giờ đây, trong cuốn sách đặc biệt này, ghi chép chính thức về BTS và tuổi trẻ của nhóm, “The Most Beautiful Moment on Life” (khoảnh khắc rực rỡ nhất trong cuộc đời) do nhà phê bình âm nhạc/văn hóa đại chúng Myeongseok Kang chắp bút trong vòng hơn 3 năm và việc phỏng vấn được thực hiện trong hai năm. BTS đã chia sẻ những câu chuyện cá nhân, hậu trường và hành trình của nhóm cho đến thời điểm hiện tại.'
        },
        {
            id: '9',
            name: 'MAP OF THE SOUL: 7 - PERSONA, SHADOW & EGO IN THE WORLD OF BTS',
            img: require('./src/img/book/83.png'),
            supplier: 'AZ Việt Nam',
            ublishing: 'Thế Giới',
            author: 'Murray Stein, Steve Buser, Leonard Cruz',
            cover: 'Bìa Cứng',
            price: '123.250 đ ',
            des:'Map of the Soul: 7 – Persona, Shadow & Ego in the world of BTS: CUỐN SÁCH GIẢI MÃ BẢN ĐỒ TÂM HỒN CỦA BTS - Trong “Intro Persona”, RM đã hát rằng: “Tôi chẳng biết mình là ai” và kết thúc với câu “Đây là tấm bản đồ của tâm hồn. Đây là bản đồ tâm hồn của tôi”. - Bạn có thực sự hiểu về BTS, về bản đồ tâm hồn của họ và những mong muốn sâu thẳm vẫn luôn đồng hành cùng họ như chiếc bóng? - Thông qua chuỗi album “Map of the Soul”, họ đã đưa ra những thông điệp ẩn giấu với hy vọng các ARMY sau khi nghe các giai điệu, lời bài hát sẽ hiểu bảy chàng trai của BTS hơn, đồng thời các ARMY cũng hiểu về chính mình hơn. - BTS đã lột bỏ chiếc mặt nạ (Persona) để người hâm mộ có thể đến gần hơn với con người thật của họ. Còn các bạn thì sao? Các bạn đã sẵn sàng để bước vào tấm bản đồ tâm hồn của BTS chưa?'
        },
        {
            id: '10',
            name: 'Kinh Tế Vĩ Mô (Ns Kinh Tế)',
            img: require('./src/img/book/84.png'),
            supplier: 'AZ Việt Nam',
            ublishing: 'Kinh tế TP.Hồ Chí Minh',
            author: 'Nguyễn Minh Tuấn , Trần Ng Mi',
            cover: 'Bìa Mềm',
            price: '61.200 đ ',
            des:'Xu thế hội nhập toàn cầu là động lực thúc đẩy sự phát triển kinh tế của các quốc gia trên thế giới. Xu hướng này vừa là một thách thức vừa là một cơ hội để các quốc gia đang trên đà phát triển như Việt Nam tự khẳng định mình. Vì vậy, sự am hiểu về các vấn đề kinh tế ở cấp vĩ mô như lạm phát, thất nghiệp, chính sách tài khoản, chính sách tiền tệ... của một quốc gia là điều hết sức cần thiết đối với sinh viên Đại học ngành Quản trị kinh doanh nói riêng và với sinh viên khối ngành Kinh tế nói chung. - Để tạo điều kiện cho sinh viên thuận tiện trong việc nghiên cứu, học tập; chúng tôi đã nghiên cứu, sưu tập và biên soạn lại một số tài liệu học tập liên quan đến các lĩnh vực trên, nhằm phục vụ cho việc giảng dạy môn học “Kinh tế vĩ mô” cho các sinh viên thuộc ngành Quản trị Kinh Doanh, Kinh tế. - Đây là lần tái bản đầu tiên, tài liệu học tập “Kinh tế vĩ mô” tuy đã được cập nhật nhưng chắc chắn không tránh khỏi những thiếu sót nhất định. Chúng tôi kính mong Quý đồng nghiệp, các bạn đọc xa gần đóng góp ý kiến để chúng tôi có thể tiếp tục sửa chữa, hoàn thiện tài liệu học tập được tốt hơn trong lần xuất bản sau.'
        },
        {
            id: '11',
            name: 'Món Quà Kinh Tế',
            img: require('./src/img/book/85.png'),
            supplier: 'NXB Trẻ',
            ublishing: 'Tổng Hợp Thành Phố Hồ Chí Minh, Trẻ, Phụ Nữ',
            author: 'Nhiều Tác Giả',
            cover: 'Bìa Mềm',
            price: '328.738 đ ',
            des:'Combo Sinh Nhật 6 - Sách Kinh Tế (Bộ 4 Cuốn) - 1. Từ Tốt Đến Vĩ Đại - Jim Collins cùng nhóm nghiên cứu đã miệt mài nghiên cứu những công ty có bước nhảy vọt và bền vững để rút ra những kết luận sát sườn, những yếu tố cần kíp để đưa công ty từ tốt đến vĩ đại. Đó là những yếu tố khả năng lãnh đạo, con người, văn hóa, kỷ luật, công nghệ… Những yếu tố này được nhóm nghiên cứu xem xét tỉ mỉ và kiểm chứng cụ thể qua 11 công ty nhảy vọt lên vĩ đại. Mỗi kết luận của nhóm nghiên cứu đều hữu ích, vượt thời gian, ý nghĩa vô cùng to lớn đối với mọi lãnh đạo và quản lý ở mọi loại hình công ty (từ công ty có nền tảng và xuất phát tốt đến những công ty mới khởi nghiệp), và mọi lĩnh vực ngành nghề. Đây là cuốn sách nên đọc đối với bất kỳ lãnh đạo hay quản lý nào! - 2. Nhà Lãnh Đạo Không Chức Danh - Suốt hơn 15 năm, Robin Sharma đã thầm lặng chia sẻ với những công ty trong danh sách Fortune 500 và nhiều người siêu giàu khác một công thức thành công đã giúp ông trở thành một trong những nhà cố vấn lãnh đạo được theo đuổi nhiều nhất thế giới. Đây là lần đầu tiên Sharma công bố công thức độc quyền này với bạn, để bạn có thể đạt được những gì tốt nhất, đồng thời giúp tổ chức của bạn có thể có những bước đột phá đến một cấp độ thành công mới trong thời đại thiên biến vạn hóa như hiện nay. - 3. Think And Grow Rich - Nghĩ Giàu Và Làm Giàu - Think and Grow Rich - Nghĩ giàu và làm giàu là một trong những cuốn sách bán chạy nhất mọi thời đại. Đã hơn 60 triệu bản được phát hành với gần trăm ngôn ngữ trên toàn thế giới và được công nhận là cuốn sách tạo ra nhiều triệu phú, một cuốn sách truyền cảm hứng thành công nhiều hơn bất cứ cuốn sách kinh doanh nào trong lịch sử. - 4. Tài Chính Cá Nhân Dành Cho Người Việt Nam - Cuốn sách “Tài chính cá nhân dành cho người Việt Nam” và bộ bài giảng trực tuyến tặng kèm, gồm tất cả những nội dung về tài chính cá nhân.'
        },
        {
            id: '12',
            name: 'Bên Nhau Trọn Đời (Tái Bản 2022)',
            img: require('./src/img/book/86.png'),
            supplier: 'Bách Việt',
            ublishing: 'Văn Học',
            author: 'Cố Mạn',
            cover: 'Bìa Mềm',
            price: '89.900 đ ',
            des:'Bên Nhau Trọn Đời - Năm 2015, “Bên nhau trọn đời” đã được chuyển thể thành phim truyền hình. Kịch bản do chính tác giả Cố Mạn và bạn thân Mặc Bảo Phi Bảo chấp bút. - Thông tin tác phẩm: Bảy năm trước, vì hiểu lầm và cả sự chen chân của Hà Dĩ Mai mà Triệu Mặc Sênh đau lòng rời bỏ Hà Dĩ Thâm, lên máy bay sang Mỹ. Cô cứ nghĩ rằng anh không đau lòng, là anh đuổi cô đi, mà đâu ngờ cuộc chia ly năm ấy đã trở thành tổn thương khó xóa nhòa trong lòng anh. - Nhiều năm sau, có rất nhiều cô gái để mắt đến Dĩ Thâm, nhưng lòng anh chẳng thể dung chứa ai ngoài cô gái đã mải miết theo đuổi anh suốt một năm ròng ở trường Đại học. - Bảy năm sau gặp lại, cô trở thành nhiếp ảnh gia của một tạp chí, còn anh là luật sư nổi tiếng được nhiều người biết đến. Họ vô tình hội ngộ tại siêu thị, rồi một lần nữa bước vào đời nhau.'
        },
    ],
}